##############对模拟数据的K-Means聚类
set.seed(12345)
x<-matrix(rnorm(n=100,mean=0,sd=1),ncol=2,byrow=TRUE)  
x[1:25,1]<-x[1:25,1]+3           
x[1:25,2]<-x[1:25,2]-4
par(mfrow=c(2,2))
plot(x,main="样本观测点的分布",xlab="",ylab="")  
set.seed(12345)
#kmeans(x=矩阵数目,centers=聚类数目或质心数目,iter.max=10,nstart=1)
#iter.max指最大迭代次数,最大为10
#当centers为一个整数时,R采用随机选择法选择质心。当迭代次数不充分大时候,
#初始质心对结果影响很大,可设置nstart为一个大于1的整数,代表重复多次抽取质心。
#kmeans结果是一个列表
#cluster:存储个观测所属的小类编号。
#centers:存储各小类质心
#totss:所有聚类变量的离差平方和。
#withinss:包含k个元素的向量,分别存储各聚类变量的类内离差平方和。
#tot.withinss:K个类的各聚类变量的类内离差平方和的总和。
#betweenss:等于totss-tot.withinss
#size:各类样本量
(KMClu1<-kmeans(x=x,centers=2,nstart=1))  
#cluter means:是质心坐标(0,17,0.48),(3.14,-3.67)
#betweenss/totss=74.6%结果可接受
plot(x,col=(KMClu1$cluster+1),main="K-Means聚类K=2",xlab="",ylab="",pch=20,cex=1.5)
points(KMClu1$centers,pch=3)
set.seed(12345)
#分成4类
KMClu2<-kmeans(x=x,centers=4,nstart=1)   
plot(x,col=(KMClu2$cluster+1),main="K-Means聚类K=4,nstart=1",xlab="",ylab="",pch=20,cex=1.5)
points(KMClu2$centers,pch=3)
#比较两个小类和4个小类的指标发现两类比四类好
KMClu1$betweenss/(2-1)/(KMClu1$tot.withinss/(50-2))
KMClu2$betweenss/(4-1)/(KMClu2$tot.withinss/(50-4))
set.seed(12345)
#这里展示了nstart的影响,nstart越大越好
KMClu2<-kmeans(x=x,centers=4,nstart=30)
plot(x,col=(KMClu2$cluster+1),main="K-Means聚类K=4,nstart=30",xlab="",ylab="",pch=20,cex=1.5)
points(KMClu2$centers,pch=3)