#PAM距离——对K均值聚类的改进。
#################PAM聚类
set.seed(12345)
x<-matrix(rnorm(n=100,mean=0,sd=1),ncol=2,byrow=TRUE) 
x[1:25,1]<-x[1:25,1]+3            
x[1:25,2]<-x[1:25,2]-4
library("cluster")
set.seed(12345)
#pam(x=矩阵或数据框,k=聚类数目,medoids=初始类质心向量,do.swap=TRUE/FALSE,stand=TRUE/FALSE)
#medoids是包含k个质心的向量。比如c(1,10)分别以第1和第10个观测点作为K=2时的初始质心。
#do.swap代表是否要做do.swap会增加计算量。
#stand是否要消除量级影响,当x是距离矩阵时该参数无效。
(PClu<-pam(x=x,k=2,do.swap=TRUE,stand=FALSE)) 
#pam返回值包括
#clustering:各个观测值所属类别
#clusion:存储各类的样本量、类内最大绝对距离、平均绝对距离和标准差。
#silinfo:存储个观测所属的类、其邻居类以及轮宽值。该值越接近1，聚类越合理
plot(x=PClu,data=x)